[LLAMA]
model_name = "meta-llama/Llama-3.2-3B-Instruct"  #This model name can be changed as per requirement! But be precise with the name and its address!!

[HF_TOKEN]
api_token = "" #Enter your HuggingFace API Token
